Bootstrap: docker
From: eddelbuettel/r2u:jammy

%post
apt-get update &&
apt-get -y install --no-install-recommends git bzip2 libglpk-dev libjpeg-dev libz-dev libxt-dev libtiff5-dev libbz2-dev libfontconfig1-dev libssl-dev cmake && rm -rf /var/lib/apt/lists/*

wget https://github.com/kusqaum/skeletal-transcriptomics/raw/main/install/install.R        

wget https://github.com/kusqaum/skeletal-transcriptomics/raw/main/install/install.txt

#install the R libraries needed
Rscript install.R
